import { useState } from 'react'
import { ArrowLeft, Check, MoreHorizontal, Play, Plus, Shuffle, Trash2 } from 'lucide-react'

function PlaylistCover({ playlist, large = false }) {
  const image = playlist.coverImage || playlist.tracks[0]?.thumbnail
  return <div className={`playlist-cover ${large ? 'large' : ''}`}>{image ? <img src={image} alt="" /> : <span className="playlist-cover-placeholder">k</span>}</div>
}

export function PlaylistPicker({ track, playlists, onAdd, onCreate, onClose }) {
  const [message, setMessage] = useState('')
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  if (!track) return null
  const handleAdd = (playlist) => {
    const added = onAdd(playlist.id, track)
    setMessage(added ? `Added to ${playlist.name}` : `${track.title} is already in ${playlist.name}`)
  }
  const createAndAdd = (event) => { event.preventDefault(); const trimmed = name.trim(); if (!trimmed) return; const playlist = onCreate({ name: trimmed, description: '', coverImage: '' }); onAdd(playlist.id, track); setMessage(`Added to ${playlist.name}`); setCreating(false); setName('') }
  return <div className="modal-backdrop" onClick={onClose}><section className="playlist-picker modal-panel" role="dialog" aria-modal="true" aria-label="Add to playlist" onClick={(event) => event.stopPropagation()}><header><div><p className="eyebrow">SAVE TRACK</p><h2>Add to playlist</h2></div><button type="button" className="modal-close" aria-label="Close" onClick={onClose}>×</button></header><p className="modal-track-name">{track.title}</p>{creating ? <form className="picker-create-form" onSubmit={createAndAdd}><input autoFocus required value={name} onChange={(event) => setName(event.target.value)} placeholder="Playlist name" /><button type="submit" className="primary-button">Create and add</button></form> : <><div className="playlist-picker-list">{playlists.map((playlist) => <button type="button" key={playlist.id} onClick={() => handleAdd(playlist)}><PlaylistCover playlist={playlist} /><span><strong>{playlist.name}</strong><small>{playlist.tracks.length} tracks</small></span><Check size={16} /></button>)}</div><button type="button" className="modal-secondary-action" onClick={() => setCreating(true)}><Plus size={16} /> Create playlist</button></>}{message && <p className="modal-message">{message}</p>}</section></div>
}

export default function Playlists({ playlists, availableTracks = [], onCreate, onUpdate, onDelete, onPlayTrack, onPlayAll, onAddTrack, onRemoveTrack }) {
  const [selectedId, setSelectedId] = useState(null)
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [editing, setEditing] = useState(null)
  const [form, setForm] = useState({ name: '', description: '', coverImage: '' })
  const selected = playlists.find((playlist) => playlist.id === selectedId)
  const openCreate = () => { setForm({ name: '', description: '', coverImage: '' }); setEditing(null); setIsCreateOpen(true) }
  const submit = (event) => { event.preventDefault(); const name = form.name.trim(); if (!name) return; if (editing) onUpdate(editing.id, { ...form, name }); else onCreate({ ...form, name }); setIsCreateOpen(false) }
  const openEdit = () => { setForm({ name: selected.name, description: selected.description, coverImage: selected.coverImage }); setEditing(selected); setIsCreateOpen(true) }
  if (selected) return <section className="library-screen playlist-detail"><button type="button" className="back-library" onClick={() => setSelectedId(null)}><ArrowLeft size={16} /> All playlists</button><div className="playlist-detail-hero"><PlaylistCover playlist={selected} large /><div><p className="eyebrow">PLAYLIST</p><h1>{selected.name}</h1><p>{selected.description || 'A collection for your mood.'}</p><small>{selected.tracks.length} tracks</small><div className="playlist-detail-actions"><button type="button" className="primary-button" onClick={() => onPlayAll(selected.tracks)}><Play size={17} fill="currentColor" /> Play all</button><button type="button" className="secondary-icon-action" aria-label="Shuffle playlist" title="Shuffle playlist" onClick={() => onPlayAll(selected.tracks, true)}><Shuffle size={17} /></button><button type="button" className="secondary-icon-action" aria-label="Edit playlist" title="Edit playlist" onClick={openEdit}><MoreHorizontal size={17} /></button></div></div></div><div className="playlist-track-list"><div className="section-heading"><h2>Tracks</h2><span className="text-button"><Plus size={15} /> Add from below</span></div>{availableTracks.length > 0 && <div className="playlist-add-tracks">{availableTracks.filter((track) => !selected.tracks.some((item) => item.videoId === track.videoId)).slice(0, 8).map((track) => <button type="button" key={track.videoId} onClick={() => onAddTrack(selected.id, track)}><Plus size={14} /> {track.title}</button>)}</div>}{selected.tracks.length ? selected.tracks.map((track) => <div className="playlist-track-row" key={track.videoId}><button type="button" className="playlist-track-play" onClick={() => onPlayTrack(track, selected.tracks)}><PlaylistCover playlist={{ tracks: [track] }} /><span><strong>{track.title}</strong><small>{track.artist}</small></span></button><button type="button" className="queue-remove" aria-label={`Remove ${track.title}`} title="Remove from playlist" onClick={() => onRemoveTrack(selected.id, track.videoId)}><Trash2 size={15} /></button></div>) : <div className="library-empty"><p>This playlist is empty. Add songs from Search or your Library.</p></div>}</div>{isCreateOpen && <PlaylistForm form={form} editing={editing} setForm={setForm} onSubmit={submit} onClose={() => setIsCreateOpen(false)} />}</section>
  return <section className="library-screen"><div className="explore-heading library-heading"><div><p className="eyebrow">YOUR MUSIC</p><h1>Playlists</h1><p className="subcopy">Small collections for the moments that matter.</p></div><button type="button" className="primary-button" onClick={openCreate}><Plus size={17} /> Create playlist</button></div>{playlists.length ? <div className="playlist-grid">{playlists.map((playlist) => <article className="playlist-card" key={playlist.id}><PlaylistCover playlist={playlist} /><div><h2>{playlist.name}</h2><p>{playlist.description || 'No description'}</p><small>{playlist.tracks.length} tracks</small></div><div className="playlist-card-actions"><button type="button" className="row-play" aria-label={`Play ${playlist.name}`} onClick={() => onPlayAll(playlist.tracks)}><Play size={15} fill="currentColor" /></button><button type="button" className="text-button" onClick={() => setSelectedId(playlist.id)}>Open</button><button type="button" className="more-button" aria-label={`Delete ${playlist.name}`} onClick={() => onDelete(playlist.id)}><Trash2 size={15} /></button></div></article>)}</div> : <div className="library-empty"><h3>No playlists yet</h3><p>Create a playlist from the button above.</p></div>}{isCreateOpen && <PlaylistForm form={form} editing={editing} setForm={setForm} onSubmit={submit} onClose={() => setIsCreateOpen(false)} />}</section>
}

function PlaylistForm({ form, editing, setForm, onSubmit, onClose }) {
  return <div className="modal-backdrop" onClick={onClose}><form className="modal-panel playlist-form" onSubmit={onSubmit} onClick={(event) => event.stopPropagation()}><header><div><p className="eyebrow">KROVI LIBRARY</p><h2>{editing ? 'Edit playlist' : 'Create playlist'}</h2></div><button type="button" className="modal-close" aria-label="Close" onClick={onClose}>×</button></header><label>Name<input autoFocus required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Morning light" /></label><label>Description <span>optional</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="A little context for this collection" /></label><label>Cover image URL <span>optional</span><input value={form.coverImage} onChange={(event) => setForm({ ...form, coverImage: event.target.value })} placeholder="https://..." /></label><footer><button type="button" className="modal-secondary-action" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">{editing ? 'Save changes' : 'Create playlist'}</button></footer></form></div>
}

